# Generated by Django 3.1.3 on 2023-07-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='key',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='clave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='clave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
