# Generated by Django 3.1.3 on 2023-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230707_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='key',
            field=models.CharField(max_length=255, verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=255, verbose_name='clave'),
        ),
    ]
