# Generated by Django 3.1.3 on 2023-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230707_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cédula'),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cédula'),
        ),
    ]
