# Generated by Django 3.1.3 on 2023-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230708_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='text_decrypt',
            field=models.TextField(blank=True, null=True, verbose_name='Texto descifrado'),
        ),
        migrations.AddField(
            model_name='user',
            name='text_decrypt',
            field=models.TextField(blank=True, null=True, verbose_name='Texto descifrado'),
        ),
    ]
