# Generated by Django 3.1.3 on 2023-06-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmeasureunit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unidad de medida'},
        ),
        migrations.AlterModelOptions(
            name='measureunit',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='measure_unit',
        ),
    ]
